[tool.poetry]
name = "turing-io"
version = "0.1.0"
description = "An environment to define and run Turing machines."
authors = ["Rom Gat <rom.gat532@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false    # Remove this when you want the project to install

keywords = ["turing", "turing machine", "turing-machine", "turing.io", "tm", "simulator", "compiler"]
classifiers = [
    "Development Status :: 1 - Planning",

    "Intended Audience :: Developers",
    "Intended Audience :: Education",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Topic :: Education",
    "Topic :: Software Development :: Compilers",
]

[tool.poetry.urls]
Repository = "https://github.com/rg-532/turing-io"

[tool.poetry.dependencies]
python = "3.12.12"
jsonpickle = "^4.1.1"
ply = "3.11"
poetry = ">=0.12"

[tool.poetry.group.dev.dependencies]
black = "^24.0"
mypy = "^1.10"
ruff = "^0.6"
pytest = "^8.0"
tabulate = "^0.9"
sphinx = "^8.2.3"


[tool.turing_io.test.schema_versions]
base = "1"
token = "1"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["-rsP"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)-8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%H:%M:%S"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
strict = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
