[project]
name = "turing-io"
version = "0.1.0"
description = "An environment to define and run Turing machines."
authors = [{ name = "Rom Gat", email = "rom.gat532@gmail.com" }]
requires-python = "==3.12.12"
readme = "README.md"
license = "MIT"
keywords = [
    "turing",
    "turing machine",
    "turing-machine",
    "turing.io",
    "tm",
    "simulator",
    "compiler",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Education",
    "Topic :: Software Development :: Compilers",
]
dependencies = [
    "jsonpickle>=4.1.1,<5",
    "ply==3.11",
]

[project.urls]
Repository = "https://github.com/rg-532/turing-io"

[dependency-groups]
dev = [
    "black>=24.0,<25",
    "mypy>=1.10,<2",
    "ruff>=0.6,<0.7",
    "pytest>=8.0,<9",
    "tabulate>=0.9,<0.10",
    "sphinx>=8.2.3,<9",
    "click>=8.3.0,<9",
]

[tool.uv]
package = false


[tool.turing_io.test.schema_versions]
base = "1"
token = "2"


[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["-rsP"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)-8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%H:%M:%S"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
strict = true
mypy_path = "src, tests, tools, typings"

[[tool.mypy.overrides]]
module = ["jsonpickle.*"]
ignore_missing_imports = true
check_untyped_defs = false
implicit_reexport = true


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
