"""This module defines schemas for JSON file_managers generated by the project (for instance, during testing).
"""
from typing import Dict, Any, TypeVar
import os
from dataclasses import dataclass, field
from pathlib import Path

import jsonpickle

from tests.compiler_tests.utils.file_managers.base_manager import FileManager

_T_Schema = TypeVar("_T_Schema", bound="GoldenFileSchema")


@dataclass
class GoldenFileSchema:
    """Most basic schema for JSON file_managers which are generated automatically.

    :ivar file_type:        Type of the file (i.e. Token list from lexer tests).
    :ivar generated_by:     Component (module, class, function) which generated the file.

    :ivar project_version:  Current version of the project (default from ``pyproject.toml``).
    :ivar schema_version:   Current version of the schema structure (set by default).
    :ivar timestamp:        Date and time of execution which created this schema (defaults to ``datetime.now()``).

    :ivar metadata:         Dictionary of added metadata on the file (defaults to empty ``dict``).

    :ivar data:             Dictionary containing stored data (also defaults to empty ``dict``).
    """
    file_type: str
    generated_by: str

    project_version: str = os.environ.get("PROJECT_VERSION", "0.0.0")
    schema_version: str = "1"
    timestamp: str = os.environ.get("EXEC_TIME", "0000-00-00 00:00:00.00000")

    metadata: Dict[str, Any] = field(default_factory=dict)

    data: Dict[str, Any] = field(default_factory=dict)


class GoldenFileManager(FileManager[_T_Schema]):
    """Implements functionality to read/write objects from JSON file_managers generated by ``jsonpickle``. The objects
    must be super-classed by :class:`schema.BaseJsonSchema` (Which defines a structure of a JSON file).
    """
    def _read_core(self, fullpath: Path) -> _T_Schema:
        return jsonpickle.decode(fullpath.read_text())

    def _write_core(self, fullpath: Path, data: _T_Schema) -> None:
        fullpath.write_text(jsonpickle.encode(data))
