"""This module defines a file manager for golden files (JSON files managed with ``jsonpickle``).
"""
from pathlib import Path

import jsonpickle

from compiler_tests.utils.files.schemas.golden_schema import GoldenFileSchema
from compiler_tests.utils.files.managers.base_manager import FileManager


class GoldenFileManager[T_Schema: GoldenFileSchema](FileManager[T_Schema]):
    """Implements functionality to read/write objects from JSON files generated by ``jsonpickle``. The objects
    must be super-classed by :class:`schema.BaseJsonSchema` (Which defines a structure of a JSON file).

    Keyword arguments to ``read()`` and ``write()`` are passed to the ``jsonpickle`` library.
    """
    def _read_core(self, fullpath: Path, **kwargs) -> T_Schema:
        defaults = dict(on_missing="error")
        defaults.update(kwargs)

        return jsonpickle.decode(fullpath.read_text(), **defaults)

    def _write_core(self, fullpath: Path, data: T_Schema, **kwargs) -> None:
        defaults = dict(indent = 2)
        defaults.update(kwargs)

        fullpath.write_text(jsonpickle.encode(data, **defaults))
