"""This module defines a file manager for golden files (JSON files managed with ``jsonpickle``).
"""
import os
from pathlib import Path
from typing import Tuple, Optional

import jsonpickle.errors

from compiler_tests.utils.files.errors import ClassNotFoundError
from compiler_tests.utils.files.schemas.golden_schema import GoldenFileSchema
from compiler_tests.utils.files.managers.base_manager import FileManager


class GoldenFileManager[T_Schema: GoldenFileSchema](FileManager[T_Schema]):
    """Implements functionality to read/write objects from JSON files generated by ``jsonpickle``. The objects
    must be super-classed by :class:`schema.BaseJsonSchema` (Which defines a structure of a JSON file).

    Keyword arguments to ``read()`` and ``write()`` are passed to the ``jsonpickle`` library.
    """
    def safe_read(
            self,
            relpath: str | os.PathLike,
            **kwargs
    ) -> Tuple[Optional[T_Schema], Optional[Exception]]:
        """Safe version of ``FileManager.read``, which also returns the exception instead of raising it.

        Only one item in the returned tuple is not set to None, based on what happened during ``read``:
            - If an exception ``cause`` was raised, the return value is ``(None,cause)``.
            - Otherwise, the return value is ``(schema,None)``.

        :param relpath: Relative path to file under this directory.
        :param kwargs:  Additional keyword parameters for ``jsonpickle.decode``.
        :return:        Tuple of (result, exc), one of which is set to ``None``.
        """
        try:
            return super().read(relpath, **kwargs), None
        except Exception as cause:
            return None, cause

    @staticmethod
    def _raise_class_not_found_error(class_name: str) -> None:
        """Helper method to raise custom :class:`ClassNotFoundError` (see that class's doc).

        :param class_name:          Name of the class which was not found.
        :raise ClassNotFoundError:  Always happens.
        """
        raise ClassNotFoundError(f"Could not find class {class_name}")

    def _read_core(self, fullpath: Path, **kwargs) -> T_Schema:
        defaults = dict(on_missing=self._raise_class_not_found_error)
        defaults.update(kwargs)

        return jsonpickle.decode(fullpath.read_text(), **defaults)

    def _write_core(self, fullpath: Path, data: T_Schema, **kwargs) -> None:
        defaults = dict(indent = 2)
        defaults.update(kwargs)

        fullpath.write_text(jsonpickle.encode(data, **defaults))
