"""'Bag of crap' style utilities.
"""

from functools import cache, wraps
from typing import TypeVar, Callable, ParamSpec

_R = TypeVar("_R")
_P = ParamSpec("_P")
_P2 = ParamSpec("_P2")


def typed_cache(func: Callable[_P, _R]) -> Callable[_P, _R]:
    """Simply adds typing support for ``functools.cache`` so that hints will appear (use as decorator).

    :param func:    Function to apply ``functools.cache`` to.
    :return:        Function with ``functools.cache`` applied to it.
    """
    return cache(func)


def pre_call_hook(pre_call_func: Callable[_P, ...],
                  *p_args: _P.args,
                  **p_kwargs: _P.kwargs) -> Callable[[Callable[[_P2], _R]], Callable[[_P2], _R]]:
    """Decorator factory which returns a decorator that calls ``pre_call_func(*p_args,**p_kwargs)`` before
    calling the decorated function.

    :param pre_call_func:   Callable to call before calling the decorated function.
    :param p_args:          Positional arguments for ``pre_call_func``.
    :return:                Decorator for the function.
    """
    def decorator(func: Callable[_P2, _R]) -> Callable[_P2, _R]:
        @wraps(func)
        def wrapper(*args: _P2.args, **kwargs: _P2.kwargs):
            pre_call_func(*p_args, **p_kwargs)
            return func(*args, **kwargs)

        return wrapper
    return decorator


def get_func_desc(func: Callable[[...], ...]) -> str:
    """Utility for generating a short description a python function ``func``.

    If some attributes of ``func`` cannot be found, they are replaced with a fixed string value. For example, a
    callable generated by ``functools.partial`` will most likely not have ``__qualname__``.

    :param func:    Function to describe.
    :return:        Function description
    """
    func_name = func.__qualname__ if hasattr(func, "__qualname__") else "<unknown>"
    func_module = func.__module__ if hasattr(func, "__module__") else "<unknown>"

    return f"{func_module}::{func_name}"
