"""This module supplies classes to manage files (read, write, check existence, move, etc.).
"""
from abc import ABC, abstractmethod
from typing import Union, TypeAlias, AnyStr, Literal, Any, Generic, TypeVar, Self
from dataclasses import dataclass
import os

from jsonpickle import encode as jp_encode, decode as jp_decode

from tests.compiler_tests.utils.files.errors import PermissionsError
from tests.compiler_tests.utils.files.schema import BaseJsonSchema

Path: TypeAlias = Union[AnyStr, os.PathLike]

_T = TypeVar("_T")
_T_Schema = TypeVar("_T_Schema", bound=BaseJsonSchema)

@dataclass
class _Permissions(object):
    read: bool = True
    write: bool = True


class FileManager(ABC, Generic[_T]):
    """Abstract class defining an interface to manage files in the directory at ``dirpath`` relative to root of
    execution. This class is generic in terms of the type of data being read from and written to files.

    :ivar dirpath:      Path to directory of files from running root.
    :ivar dir_exists:   Boolean flag indicating whether directory existence was checked.
    :ivar perms:        Permissions dataclass defining permissions on files in the directory.
    """
    def __init__(self, dirpath: Path):
        self.dirpath: Path = dirpath
        self.dir_exists: bool = False
        self.perms = _Permissions

    def set_perms(self, perms: Literal["r", "w", "rw", "wr"]) -> Self:
        self.perms.read = "r" in perms
        self.perms.write = "w" in perms

        return self

    @abstractmethod
    def read(self, filepath: Path) -> _T:
        ...

    @abstractmethod
    def write(self, filepath: Path, data: _T, allow_overwrite: bool = False) -> None:
        ...


class TextFileManager(FileManager[str]):
    """Implements simple functionality to read/write text files.
    """
    def read(self, filepath: Path) -> str:
        if not self.perms.read:
            raise PermissionsError(f"Directory {self.dirpath} does not have read permission.")

        filepath = os.path.join(self.dirpath, filepath)

        with open(filepath, mode="r") as f:
            result = f.read()

        return result

    def write(self, filepath: Path, data: str, allow_overwrite: bool = False) -> None:
        if not self.perms.write:
            raise PermissionsError(f"Directory {self.dirpath} does not have write permission.")

        if not self.dir_exists:
            os.makedirs(self.dirpath, exist_ok=True)
            self.dir_exists = True

        filepath = os.path.join(self.dirpath, filepath)
        mode = "w" if allow_overwrite else "x"

        with open(filepath, mode=mode) as f:
            f.write(data)


class JsonFileManager(FileManager[_T_Schema]):
    """Adds functionality to read/write objects from JSON files generated by ``jsonpickle``. The objects must be
    super-classed by :class:`schema.BaseJsonSchema` (Which defines a structure of a JSON file).

    Decorates the sibling class :class:`TextFileManager` by adding `jsonpickle.decode()` calls on read
    and ``jsonpickle.encode()`` calls on write.

    :ivar text_mgr: Wrapped :class:`TextFileManager` to delegate work to.
    """
    def __init__(self, dirpath: Path):
        super().__init__(dirpath)
        self.text_mgr = TextFileManager(dirpath)

    def read(self, filepath: Path) -> Any:
        result = self.text_mgr.read(filepath)
        return jp_decode(result)

    def write(self, filepath: Path, data: Any, allow_overwrite: bool = False) -> None:
        data = jp_encode(data)
        return self.text_mgr.write(filepath, data, allow_overwrite)









